/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_0b0 0x00u  /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_0b00 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTC6 (number 42), LPUART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITLPUART_LPUART0_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLPUART_LPUART0_RX_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLPUART_LPUART0_RX_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC7 (number 43), LPUART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITLPUART_LPUART0_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLPUART_LPUART0_TX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITLPUART_LPUART0_TX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);

/*! @name PORTB3 (number 19), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_LED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_LED_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_LED_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_LED_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC1 (number 37), LED_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_LED_R_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_R_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_R_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_LED_R_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_LED_R_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_LED_R_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB2 (number 18), LED_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_LED_B_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_B_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_B_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_LED_B_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_LED_B_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_LED_B_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTA16 (number 4), LED_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_LED_G_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_G_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_LED_G_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_LED_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_LED_G_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_LED_G_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

/*! @name PORTB18 (number 23), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW2_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC2 (number 38), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW3_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW3_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtons(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
