PRIMARY_SERVICE(service_gatt, gBleSig_GenericAttributeProfile_d)
        CHARACTERISTIC(char_service_changed, gBleSig_GattServiceChanged_d, (gGattCharPropIndicate_c) )
            VALUE(value_service_changed, gBleSig_GattServiceChanged_d, (gPermissionNone_c), 4, 0x00, 0x00, 0x00, 0x00)
            CCCD(cccd_service_changed)

PRIMARY_SERVICE(service_gap, gBleSig_GenericAccessProfile_d)
    CHARACTERISTIC(char_device_name, gBleSig_GapDeviceName_d, (gGattCharPropRead_c |gGattCharPropWrite_c ) )
            VALUE(value_device_name, gBleSig_GapDeviceName_d, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 12, "TWIG_BLE_ODO")
    CHARACTERISTIC(char_appearance, gBleSig_GapAppearance_d, (gGattCharPropRead_c) )
            VALUE(value_appearance, gBleSig_GapAppearance_d, (gPermissionFlagReadable_c), 2, UuidArray(gUnknown_c))
    CHARACTERISTIC(char_ppcp, gBleSig_GapPpcp_d, (gGattCharPropRead_c) )
            VALUE(value_ppcp, gBleSig_GapPpcp_d, (gPermissionFlagReadable_c), 8, 0x0A, 0x00, 0x10, 0x00, 0x64, 0x00, 0xE2, 0x04)

PRIMARY_SERVICE(service_battery, gBleSig_BatteryService_d)
    CHARACTERISTIC(char_battery_level, gBleSig_BatteryLevel_d, (gGattCharPropNotify_c | gGattCharPropRead_c))
        VALUE(value_battery_level, gBleSig_BatteryLevel_d, (gPermissionFlagReadable_c), 1, 0x5A)
        DESCRIPTOR(desc_bat_level, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x04, 0x00, 0xAD, 0x27, 0x01, 0x01, 0x00)
        CCCD(cccd_battery_level)

PRIMARY_SERVICE(service_device_info, gBleSig_DeviceInformationService_d)
    CHARACTERISTIC(char_manuf_name, gBleSig_ManufacturerNameString_d, (gGattCharPropRead_c) )
        VALUE(value_manuf_name, gBleSig_ManufacturerNameString_d, (gPermissionFlagReadable_c), sizeof(MANUFACTURER_NAME)-1, MANUFACTURER_NAME)
    CHARACTERISTIC(char_model_no, gBleSig_ModelNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_model_no, gBleSig_ModelNumberString_d, (gPermissionFlagReadable_c), 13, "TWIG BLE Demo")
    CHARACTERISTIC(char_serial_no, gBleSig_SerialNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_serial_no, gBleSig_SerialNumberString_d, (gPermissionFlagReadable_c), 7, "BLESN01")
    CHARACTERISTIC(char_hw_rev, gBleSig_HardwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_hw_rev, gBleSig_HardwareRevisionString_d, (gPermissionFlagReadable_c), sizeof(BOARD_NAME)-1, BOARD_NAME)
    CHARACTERISTIC(char_fw_rev, gBleSig_FirmwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_fw_rev, gBleSig_FirmwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.0.0")
    CHARACTERISTIC(char_sw_rev, gBleSig_SoftwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_sw_rev, gBleSig_SoftwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.0.0")
    CHARACTERISTIC(char_system_id, gBleSig_SystemId_d, (gGattCharPropRead_c) )
        VALUE(value_system_id, gBleSig_SystemId_d, (gPermissionFlagReadable_c), 8, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x9F, 0x04, 0x00)

PRIMARY_SERVICE_UUID128(service_odometer, uuid_service_live_data)
	CHARACTERISTIC_UUID128(char_temp1, uuid_char_temp1, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_temp1, uuid_char_temp1, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp1, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 1")
		DESCRIPTOR(dec_temp1_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp1)
	CHARACTERISTIC_UUID128(char_temp2, uuid_char_temp2, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_temp2, uuid_char_temp2, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp2, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 2")
		DESCRIPTOR(dec_temp2_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp2)
	CHARACTERISTIC_UUID128(char_temp3, uuid_char_temp3, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_temp3, uuid_char_temp3, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp3, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 3")
		DESCRIPTOR(dec_temp3_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp3)
	CHARACTERISTIC_UUID128(char_battv, uuid_char_battv, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128_VARLEN(value_battv, uuid_char_battv, (gPermissionFlagReadable_c), 2, 2, 0x5A)
		DESCRIPTOR(desc_battv, 0x2901U, (gPermissionFlagReadable_c), 13, "Battery V")
		DESCRIPTOR(dec_battv_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x06, 0xFD, 0x28, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_battv)
	CHARACTERISTIC_UUID128(char_batti, uuid_char_batti, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_batti, uuid_char_batti, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_batti, 0x2901U, (gPermissionFlagReadable_c), 13, "Battery I")
		DESCRIPTOR(dec_batti_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0E, 0xFF, 0x04, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_batti)
	CHARACTERISTIC_UUID128(char_accellx, uuid_char_accellx, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_accellx, uuid_char_accellx, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_accellx, 0x2901U, (gPermissionFlagReadable_c), 13, "Accell X")
		DESCRIPTOR(dec_accellx_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0E, 0xFD, 0x13, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_accellx)
	CHARACTERISTIC_UUID128(char_accelly, uuid_char_accelly, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_accelly, uuid_char_accelly, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_accelly, 0x2901U, (gPermissionFlagReadable_c), 13, "Accell Y")
		DESCRIPTOR(dec_accelly_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0E, 0xFD, 0x13, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_accelly)
	CHARACTERISTIC_UUID128(char_accellz, uuid_char_accellz, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_accellz, uuid_char_accellz, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_accellz, 0x2901U, (gPermissionFlagReadable_c), 13, "Accell Z")
		DESCRIPTOR(dec_accellz_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0E, 0xFD, 0x13, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_accellz)
	CHARACTERISTIC_UUID128(char_jerkx, uuid_char_jerkx, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_jerkx, uuid_char_jerkx, (gPermissionFlagReadable_c), 4, 0x5A)
		DESCRIPTOR(desc_jerkx, 0x2901U, (gPermissionFlagReadable_c), 13, "Jerk X")
		DESCRIPTOR(dec_jerkx_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x10, 0xFF, 0x00, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_jerkx)
	CHARACTERISTIC_UUID128(char_jerky, uuid_char_jerky, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_jerky, uuid_char_jerky, (gPermissionFlagReadable_c), 4, 0x5A)
		DESCRIPTOR(desc_jerky, 0x2901U, (gPermissionFlagReadable_c), 13, "Jerk Y")
		DESCRIPTOR(dec_jerky_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x10, 0xFF, 0x00, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_jerky)
	CHARACTERISTIC_UUID128(char_jerkz, uuid_char_jerkz, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_jerkz, uuid_char_jerkz, (gPermissionFlagReadable_c), 4, 0x5A)
		DESCRIPTOR(desc_jerkz, 0x2901U, (gPermissionFlagReadable_c), 13, "Jerk Z")
		DESCRIPTOR(dec_jerkz_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x10, 0xFF, 0x00, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_jerkz)
	CHARACTERISTIC_UUID128(char_diag, uuid_char_diag, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_UUID128(value_diag, uuid_char_diag, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_diag, 0x2901U, (gPermissionFlagReadable_c), 13, "Diagnostic")
		DESCRIPTOR(dec_diag_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x06, 0x00, 0x00, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_diag)
	CHARACTERISTIC_UUID128(char_zero_cal, uuid_char_zero_cal, (gGattCharPropNotify_c | gGattCharPropRead_c | gGattCharPropWrite_c))
		VALUE_UUID128(value_zero_cal, uuid_char_zero_cal, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_zero_cal, 0x2901U, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 8, "Zero Cal")
		CCCD(cccd_zero_cal)
