PRIMARY_SERVICE(service_gatt, gBleSig_GenericAttributeProfile_d)
        CHARACTERISTIC(char_service_changed, gBleSig_GattServiceChanged_d, (gGattCharPropIndicate_c) )
            VALUE(value_service_changed, gBleSig_GattServiceChanged_d, (gPermissionNone_c), 4, 0x00, 0x00, 0x00, 0x00)
            CCCD(cccd_service_changed)

PRIMARY_SERVICE(service_gap, gBleSig_GenericAccessProfile_d)
    CHARACTERISTIC(char_device_name, gBleSig_GapDeviceName_d, (gGattCharPropRead_c |gGattCharPropWrite_c ) )
            VALUE(value_device_name, gBleSig_GapDeviceName_d, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 12, "TWIG_BLE_ODO")
    CHARACTERISTIC(char_appearance, gBleSig_GapAppearance_d, (gGattCharPropRead_c) )
            VALUE(value_appearance, gBleSig_GapAppearance_d, (gPermissionFlagReadable_c), 2, UuidArray(gUnknown_c))
    CHARACTERISTIC(char_ppcp, gBleSig_GapPpcp_d, (gGattCharPropRead_c) )
            VALUE(value_ppcp, gBleSig_GapPpcp_d, (gPermissionFlagReadable_c), 8, 0x0A, 0x00, 0x10, 0x00, 0x64, 0x00, 0xE2, 0x04)

PRIMARY_SERVICE(service_battery, gBleSig_BatteryService_d)
    CHARACTERISTIC(char_battery_level, gBleSig_BatteryLevel_d, (gGattCharPropNotify_c | gGattCharPropRead_c))
        VALUE(value_battery_level, gBleSig_BatteryLevel_d, (gPermissionFlagReadable_c), 1, 0x5A)
        DESCRIPTOR(desc_bat_level, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x04, 0x00, 0xAD, 0x27, 0x01, 0x01, 0x00)
        CCCD(cccd_battery_level)

PRIMARY_SERVICE(service_device_info, gBleSig_DeviceInformationService_d)
    CHARACTERISTIC(char_manuf_name, gBleSig_ManufacturerNameString_d, (gGattCharPropRead_c) )
        VALUE(value_manuf_name, gBleSig_ManufacturerNameString_d, (gPermissionFlagReadable_c), sizeof(MANUFACTURER_NAME)-1, MANUFACTURER_NAME)
    CHARACTERISTIC(char_model_no, gBleSig_ModelNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_model_no, gBleSig_ModelNumberString_d, (gPermissionFlagReadable_c), 13, "TWIG BLE Demo")
    CHARACTERISTIC(char_serial_no, gBleSig_SerialNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_serial_no, gBleSig_SerialNumberString_d, (gPermissionFlagReadable_c), 7, "BLESN01")
    CHARACTERISTIC(char_hw_rev, gBleSig_HardwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_hw_rev, gBleSig_HardwareRevisionString_d, (gPermissionFlagReadable_c), sizeof(BOARD_NAME)-1, BOARD_NAME)
    CHARACTERISTIC(char_fw_rev, gBleSig_FirmwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_fw_rev, gBleSig_FirmwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.0.0")
    CHARACTERISTIC(char_sw_rev, gBleSig_SoftwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_sw_rev, gBleSig_SoftwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.0.0")
    CHARACTERISTIC(char_system_id, gBleSig_SystemId_d, (gGattCharPropRead_c) )
        VALUE(value_system_id, gBleSig_SystemId_d, (gPermissionFlagReadable_c), 8, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x9F, 0x04, 0x00)

PRIMARY_SERVICE(service_odometer, 0x0001)
	CHARACTERISTIC(char_temp1, 0x0002, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE(value_temp1, 0x0002, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp1, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 1")
		DESCRIPTOR(dec_temp1_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp1)
	CHARACTERISTIC(char_temp2, 0x0003, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE(value_temp2, 0x0003, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp2, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 2")
		DESCRIPTOR(dec_temp2_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp2)
	CHARACTERISTIC(char_temp3, 0x0004, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE(value_temp3, 0x0004, (gPermissionFlagReadable_c), 1, 0x5A)
		DESCRIPTOR(desc_temp3, 0x2901U, (gPermissionFlagReadable_c), 13, "Temperature 3")
		DESCRIPTOR(dec_temp3_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0C, 0x00, 0x2F, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_temp3)
	CHARACTERISTIC(char_battv, 0x0005, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE_VARLEN(value_battv, 0x0005, (gPermissionFlagReadable_c), 2, 2, 0x5A)
		DESCRIPTOR(desc_battv, 0x2901U, (gPermissionFlagReadable_c), 13, "Battery V")
		DESCRIPTOR(dec_battv_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x06, 0xFD, 0x28, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_battv)
	CHARACTERISTIC(char_batti, 0x0006, (gGattCharPropNotify_c | gGattCharPropRead_c))
		VALUE(value_batti, 0x0006, (gPermissionFlagReadable_c), 2, 0x5A)
		DESCRIPTOR(desc_batti, 0x2901U, (gPermissionFlagReadable_c), 13, "Battery I")
		DESCRIPTOR(dec_batti_format, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x0E, 0xFF, 0x04, 0x27, 0x00, 0x00, 0x00)
		CCCD(cccd_batti)
